### ISSUE TITLE
Support local LLMs?

### ISSUE THREAD

**Issue by cori** [tbckr/sgpt#117]
I'm running some models using oobabooga/text-generation-webui which is capable of presenting an OpenAI-compatible API. I'm able to run this, for instance, with `sgpt` by setting an env var for `OPENAI_API_BASE`, which some clients naturally respect. It looks like `github.com/sashabaranov/go-openai` doesn't automatically support it but offers a reasonably easy on-ramp.

If there's interest but no time I might be able to put together a PR - not a `go` engineer, but i imagine I could parse this task.

**Comment by tbckr** [comment]
Hi,
thanks for your request! I am currently rewriting the entire application and will release it as version 2.x. It is probably a good idea to wait until the development for version 2.x is complete. It will probably take a maximum of 2 more weeks until the release is ready - there are still some [minor bugs](https://github.com/tbckr/sgpt/milestone/1) that need to be fixed.

Feel free to implement this feature and create a PR - I will look into it. Thanks for your contribution!

**Comment by tbckr** [comment]
Version 2.0.0 has been released - feel free to come up with a solution

**Comment by tbckr** [comment]
I implemented this feature - let me know, if there are any issues

**Comment by cori** [comment]
That looks perfect - i'll give it a try. Thanks a ton!!
