### ISSUE TITLE
Mutli-User permissions issues

### ISSUE THREAD

**Issue by dhemiwc** [tbckr/sgpt#162]
### What happened?

I have two users in the same group, userA:groupA userB:groupA

It seems like if i initially run the command `sgpt --repl temp` with userA, it is creating `/tmp` files with group readonly access. 

when i run the same command with userB, i end up getting a permission error for a file `/tmp/chat_cache/temp`

if i `chmod -R 755` that directory, i then get another permission error

`PermissionError: [Errno 13] Permission denied: '/tmp/cache/8a41ee0f39f8de332fd4f3488529d2b8`

that file wasn't there when i checked. 

I also tried the `--no-cache` flag but i still got the same permission error. 

I suggest that the cache files are unique to the user running the command, or that they are given group write access or whatever they need to work. 

### How can we reproduce this?

sgpt --repl temp

switch to another user

sgpt --repl temp

### sgpt version

```bash
Not sure, installed this only a few weeks ago though.
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tbckr** [comment]
Hey, thanks for getting in touch.
It looks like you are using shell-gpt in Python (https://github.com/TheR1D/shell_gpt). Please create a corresponding issue there, as it is a different tool.
