### ISSUE TITLE
What version of gpt does it use

### ISSUE THREAD

**Issue by Am0stafa** [tbckr/sgpt#182]
### What happened?

.

### How can we reproduce this?

.

### sgpt version

```bash
.
```

### Search

- [X] I did search for other open and closed issues before opening this

### Project

- [X] I have verified that I am using the Go implementation of SGPT (this project) and that it is not another project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

.

**Comment by tbckr** [comment]
Hi,
the program uses the GPT version that you specify on the command line. If you have any further questions, please use the [Discussions](https://github.com/tbckr/sgpt/discussions), as your question is not a bug or feature request.
Have a nice weekend.
