### ISSUE TITLE
"No stream" mode does not work

### ISSUE THREAD

**Issue by johnd0e** [tbckr/sgpt#249]
### What happened?

There is an command line option to "--stream" output.
But even when I do not specify it - the output is also streamed.

### How can we reproduce this?

```
sgpt "tell me a story"
```

As there is no options, I expect the output appears all at once, but it is streamed instead.

### sgpt version

```bash
2.13.0
```

### Search

- [X] I did search for other open and closed issues before opening this

### Project

- [X] I have verified that I am using the Go implementation of SGPT (this project) and that it is not another project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tbckr** [comment]
Hey, thank you for your bug report. Could you please share your configuration with me?
You can get your current config with the `sgpt config show` command.

**Comment by johnd0e** [comment]
```
maxtokens: 2048
model: gpt-4
stream: true
temperature: "0.7"
topp: "1"
```

And after reading https://sgpt.readthedocs.io/en/latest/configuration/, I now see the point:

> These options override the default values for the corresponding command line options.

But that seems not good to me.
The common pattern is opposite: commandline options, being dynamic, should have higher priority over static config file.

**Comment by tbckr** [comment]
You are correct. What you describe is the intended behavior and the implemented state. If you do not want your response to be streamed, remove the entry from the config file or set it to false. The default for streaming is false.

If you specify the stream flag from the command line, the response is streamed. See the help output for more information.

The command line flags override the configuration values.
