### ISSUE TITLE
`--version` command line option

### ISSUE THREAD

**Issue by johnd0e** [tbckr/sgpt#250]
### Is your feature request related to a problem? Please describe.

There is no easy way to know version of tgpt.
But is required e.g. when I open bug report here.

### Describe the solution you'd like

- `--version` command line option
- or/and show version when executing with `--help` option, or without any option at all

### Search

- [X] I did search for other open and closed issues before opening this

### Project

- [X] I have verified that I am using the Go implementation of SGPT (this project) and that it is not another project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tbckr** [comment]
Hey, thanks for your request.
sgpt has a version subcommand: `sgpt version`
This will print out the current version. This is also documented in the help message and during the creation of the bug report.

**Comment by johnd0e** [comment]
> sgpt has a version subcommand: sgpt version

Indeed!
Still, `--version` options is more common, so...
