### ISSUE TITLE
SGPT NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not have access to it.'

### ISSUE THREAD

**Issue by Tech9ace** [tbckr/sgpt#256]
### What happened?

installed sgpt and insert API key 
now i have this Sgpt error 
![Screenshot_2024-06-05_18-27-33](https://github.com/tbckr/sgpt/assets/104791629/28f9a1c6-0d1c-48bf-aef0-8baa2ae8fc29)

what is the command to switch the model enter "sgpt --model" ? whats the command i need?

NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not have access to it.'

### How can we reproduce this?

![Screenshot_2024-06-05_18-27-33](https://github.com/tbckr/sgpt/assets/104791629/57e12187-413f-4923-b9e8-5e130c33c0a2)

### sgpt version

```bash
ShellGPT 1.4.3
```

### Search

- [X] I did search for other open and closed issues before opening this

### Project

- [X] I have verified that I am using the Go implementation of SGPT (this project) and that it is not another project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

thank u for help :)

**Comment by tbckr** [comment]
Hey, thanks for reaching out.
The error message looks like you are using shell-gpt in [Python](https://github.com/TheR1D/shell_gpt). Please create a corresponding issue there, as it is a different tool.

**Comment by Tech9ace** [comment]
do i need model to enter in --model (witch model?)

**Comment by tbckr** [comment]
I am sorry, but you are referring to another software. I can't help you with that, because I know nothing about the Python shell-gpt implementation. Please ask for support at: https://github.com/TheR1D/shell_gpt

**Comment by Tech9ace** [comment]
ok thank u i just finde manuells how to install it in Pip
