### ISSUE TITLE
Error: open : no such file or directory

### ISSUE THREAD

**Issue by hogmeade** [tbckr/sgpt#275]
### What happened?

After creating a chat sessions by "sgpt sh --chat ls-files "sort by name", I ran the "sgpt chat ls", but it returns "open : no such file or directory". It is supposed to return list of sessions including the "ls-files".

### How can we reproduce this?

sgpt sh --chat ls-files "sort by name"
sgpt chat ls

### sgpt version

```bash
v2.14.1
```

### Search

- [X] I did search for other open and closed issues before opening this

### Project

- [X] I have verified that I am using the Go implementation of SGPT (this project) and that it is not another project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tbckr** [comment]
Thanks for opening the bug! I was able to reproduce this error and will have a look at it.
