### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by DomDomDim** [tbckr/sgpt#86]
I have the api_key exported as an environment variable, until yesterday everything was working normally, suddenly all the requests that the program makes result in status code (429) Client Error, I already changed the chat and it didn't solve it :)

**Comment by tbckr** [comment]
What does the error message say? It is possible that you do not have any API credits left

**Comment by DomDomDim** [comment]
it's free api key, it worked normally

Em sex., 2 de jun. de 2023 12:48, Tim ***@***.***> escreveu:

**Comment by tbckr** [comment]
OpenAI does not provide free api keys. When you first login to the OpenAI website, you get free credits that allow you to test the API for a period of 3 months. After that, you have to switch to a paid account with payment information. You can find more information here: https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial

**Comment by matthiasg** [comment]
I have the exact same problem now though, the key is valid, openai works fine, it is a paid account etc. Any other idea ?

**Comment by tbckr** [comment]
OpenAI recently migrated my account to a prepaid account: https://help.openai.com/en/articles/8264644-what-is-prepaid-billing
Do you know what type of account you have? If you have a prepaid account: Do you have enough credits?

**Comment by matthiasg** [comment]
i have a personal account 'pay-as-you-go' and it seems they disabled auto-recharge wasnt a problem in december ... interesting. thanks. it also did not refill when auto-recharge was enabled. i had to manually add money to the balance.

sadly i still get 429 quota exceeded. even though i used nothing (17 tokens on gpt3.5 and 19 on gpt4)

**Comment by matthiasg** [comment]
i filed a bug with openai. this is not on sgpt

**Comment by tbckr** [comment]
Alright, thanks for letting me know!
