### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dimagoldin** [tbckr/sgpt#95]
When running behind corporate firewall and running using either cli
``` sgpt --code "test"```
i get a long python error about certificats
here is a screenshot of the ending
![image](https://github.com/tbckr/sgpt/assets/32038657/dca07f27-6cc8-40c8-a69c-19cb233e5b9a)

 or through docker 
 ```
 docker run --rm -e OPENAI_API_KEY=${OPENAI_API_KEY} ghcr.io/tbckr/sgpt:latest code "test"
 ```
 i get this error:
 ```Post "https://api.openai.com/v1/chat/completions": tls: failed to verify certificate: x509: certificate signed by unknown authority```
 
![image](https://github.com/tbckr/sgpt/assets/32038657/7653630e-bad7-4669-8d25-53c50b9f6965)

but calling openai api via curl has no problems:
![image](https://github.com/tbckr/sgpt/assets/32038657/bda40419-dca8-407d-a2bd-15898c733d18)

im running on ubuntu 22.04 wsl2 on windows 11
everything up to date and ca-certs installed

no such problem when moving to a different network (even through corpo vpn)

**Comment by tbckr** [comment]
Hey, thanks for reaching out.
To me, the first error message looks like the shell-gpt in Python ([https://github.com/TheR1D/shell_gpt](https://github.com/TheR1D/shell_gpt)). Please create a corresponding issue there, as it is a different tool.
Regarding the error in the Docker image: The Docker image only contains the commonly used CA certificates provided by [this alpine package](https://pkgs.alpinelinux.org/package/edge/main/x86/ca-certificates-bundle). It looks to me like you are using a proxy at your company that also breaks up and analyses the TLS traffic. This is why the company's own certificate is used. It seems that your VPN setup is not using this proxy. The curl command uses the custom CA certificate.
Right now there is no option to provide custom certificates.
